const colors = {
  light: {
    text: "#111111",
    tint: "#1B3A6B",
    background: "#F8F8F8",
    foreground: "#111111",
    card: "#FFFFFF",
    cardForeground: "#111111",
    primary: "#1B3A6B",
    primaryForeground: "#FFFFFF",
    secondary: "#F0F0F4",
    secondaryForeground: "#111111",
    muted: "#E8E8EE",
    mutedForeground: "#6E6E7A",
    accent: "#1B3A6B",
    accentForeground: "#FFFFFF",
    destructive: "#B03030",
    destructiveForeground: "#FFFFFF",
    border: "#E0E0E8",
    input: "#E8E8EE",
    surface: "#FFFFFF",
    surfaceElevated: "#F8F8F8",
  },
  dark: {
    text: "#111111",
    tint: "#1B3A6B",
    background: "#F8F8F8",
    foreground: "#111111",
    card: "#FFFFFF",
    cardForeground: "#111111",
    primary: "#1B3A6B",
    primaryForeground: "#FFFFFF",
    secondary: "#F0F0F4",
    secondaryForeground: "#111111",
    muted: "#E8E8EE",
    mutedForeground: "#6E6E7A",
    accent: "#1B3A6B",
    accentForeground: "#FFFFFF",
    destructive: "#B03030",
    destructiveForeground: "#FFFFFF",
    border: "#E0E0E8",
    input: "#E8E8EE",
    surface: "#FFFFFF",
    surfaceElevated: "#F8F8F8",
  },
  radius: 10,
};

export default colors;
